name: flappypip
description: flappypip Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.16.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.1.0
  flame_audio: 1.3.0
  audioplayers: ^1.1.0

flutter:
  assets:
    - assets/images/
    - assets/audio/